'use strict';

/**
 * emulator/cdl/enums.js
 *
 * WRAM enums, states and bit flags as export assets, from ram.asm's guesses
 * (wram-export.js classify) plus the values each address was seen holding:
 *   enums.asm   `!enum_7E0ADB_05 = $05` per value; for a state that indexes a
 *               jump table, each value names the handler it dispatches to
 *   enums.json  the same for tools
 * A state's handler comes from the dispatch after its load (lda $x / asl / tax /
 * jsr ($table,x)): entry = table[value * 2] in the dispatching instruction's bank.
 */

const { hex } = require('./rom-map');
const { decodeAt } = require('./disasm');
const { buildWramReport } = require('./wram-export');
const { EXT_HEAD, XR } = require('./xref-index');

const WALK = 6;

function findDispatch(rom, lib, map, accessors) {
    for (const a of accessors) {
        if (!(a.flags & XR.READ)) continue;
        let off = map.busToRom(a.pc);
        if (off < 0 || !(lib.ext[off] & EXT_HEAD)) continue;
        const first = decodeAt(rom, off, lib.cdl[off], lib.ext[off]);
        if (!first || !/^LD[AXY]$/.test(first.mnemonic)) continue;
        let shift = 0, reg = first.mnemonic[2];
        off += first.len;
        for (let n = 0; n < WALK && (lib.ext[off] & EXT_HEAD); n++) {
            const ins = decodeAt(rom, off, lib.cdl[off], lib.ext[off]);
            if (!ins) break;
            if (ins.mnemonic === 'ASL' && ins.mode === 'acc' && reg === 'A') shift++;
            else if (ins.mnemonic === 'TAX' && reg === 'A') reg = 'X';
            else if ((ins.mnemonic === 'JMP' || ins.mnemonic === 'JSR') && ins.mode === 'iabsx' && reg === 'X') {
                const bank = map.canonical(off) & 0xFF0000;
                return { site: map.canonical(off), table: bank | ins.operand, scale: shift ? 1 << shift : 1 };
            } else if (!/^(AND|CLC|SEC|REP|SEP|XBA)$/.test(ins.mnemonic)) break;
            off += ins.len;
        }
    }
    return null;
}

function buildEnums(lib, romInput) {
    const rom = romInput.length % 1024 === 512 ? romInput.subarray(512) : romInput;
    const { entries, index, map } = buildWramReport(lib, rom);
    const out = [];
    for (const e of entries) {
        const kinds = e.notes.map(n => (n.startsWith('enum') ? 'enum' : n.startsWith('state') ? 'state' : n.startsWith('bit flags') ? 'flags' : null)).filter(Boolean);
        if (!kinds.length) continue;
        const values = e.values || [];
        const item = { addr: 0x7E0000 + e.addr, name: 'wram_' + hex(0x7E0000 + e.addr, 6), kind: kinds[0], width: e.flags & XR.WORD ? 2 : 1,
            notes: e.notes, values: values.map(v => ({ value: v })), writers: [], readers: [] };
        for (const a of e.acc) (a.flags & XR.WRITE ? item.writers : item.readers).push(index.describePc(a.pc));
        if (item.kind === 'state') {
            const d = findDispatch(rom, lib, map, e.acc);
            if (d) {
                item.dispatch = { site: d.site, table: d.table };
                for (const v of item.values) {
                    const o = map.busToRom(d.table + v.value * d.scale);
                    if (o < 0 || o + 1 >= rom.length) continue;
                    const target = (d.table & 0xFF0000) | rom[o] | (rom[o + 1] << 8);
                    const t = map.busToRom(target);
                    v.handler = (t >= 0 && index.labelName(t)) || '$' + hex(target, 6);
                }
            }
        }
        if (item.kind === 'flags') {
            const bits = values.reduce((m, v) => m | v, 0);
            item.bits = [0, 1, 2, 3, 4, 5, 6, 7].filter(b => bits & (1 << b));
        }
        out.push(item);
    }
    return out;
}

function enumsAsm(enums) {
    const lines = ['; Generated by Everscript from the CDL library: WRAM enums, states and bit flags.',
        '; Values are every value written while recording; rename the defines you identify.', ''];
    for (const e of enums) {
        lines.push(`; $${hex(e.addr, 6)} ${e.width === 2 ? 'word' : 'byte'}: ${e.notes.join('; ')}`);
        if (e.writers.length) lines.push(';   written by ' + e.writers.slice(0, 4).join(', ') + (e.writers.length > 4 ? ', +' + (e.writers.length - 4) : ''));
        if (e.readers.length) lines.push(';   read by ' + e.readers.slice(0, 4).join(', ') + (e.readers.length > 4 ? ', +' + (e.readers.length - 4) : ''));
        if (e.dispatch) lines.push(`;   dispatch at $${hex(e.dispatch.site, 6)} through $${hex(e.dispatch.table, 6)}`);
        if (e.kind === 'flags') {
            for (const b of e.bits) lines.push(`!flag_${hex(e.addr, 6)}_bit${b} = $${hex(1 << b, 2)}`);
        } else {
            for (const v of e.values) lines.push(`!enum_${hex(e.addr, 6)}_${hex(v.value, 2)} = $${hex(v.value, 2)}`.padEnd(32) + (v.handler ? '; -> ' + v.handler : ''));
        }
        lines.push('');
    }
    return lines.join('\n');
}

module.exports = { buildEnums, enumsAsm };
