'use strict';

/**
 * emulator/cdl/table-assets.js
 *
 * Detected ROM lookup tables (tables.js) -> editable assets in the Asar export:
 *   tables/tbl_XXXXXX.asm   one per table: header (shape, index source, result,
 *                           readers) and one line per entry (`dw` / `db` per field)
 *   tables/tables.json      manifest for tools: offset, bus, entry size, fields, values
 *   tables/tables.h         C arrays / record structs for a decomp
 * Each table becomes a known region whose bank file does `incsrc` of its asset,
 * so the build is still byte-exact and editing a value only changes that value.
 * A table only becomes an asset when it is safe: no byte inside ran as code, it
 * does not overlap a known region or another table, stays in one bank, and the
 * recorded indices cover it densely enough to trust its length.
 */

const { hex } = require('./rom-map');
const { tableTitle } = require('./tables');

const CDL_CODE = 0x01;
const MIN_BYTES = 4;
const DENSITY = 8;        // at least one recorded index per 8 entries

/** Segments covering one record: fields where they fit, bytes elsewhere. */
function recordLayout(t) {
    const segs = [];
    const fields = t.fields.slice().sort((a, b) => a.at - b.at);
    let at = 0;
    for (const f of fields) {
        if (f.at < at || f.at + f.width > t.size) continue;
        for (; at < f.at; at++) segs.push({ at, width: 1, field: false });
        segs.push({ at, width: f.width, field: true });
        at += f.width;
    }
    for (; at < t.size; at++) segs.push({ at, width: 1, field: false });
    return segs;
}

function readValue(rom, off, width) {
    return width === 2 ? rom[off] | (rom[off + 1] << 8) : rom[off];
}

function assetText(t, rom, map, index, name) {
    const segs = recordLayout(t);
    const site = t.fields[0].sites[0];
    const lines = [
        `; ${name} - ${tableTitle(t, map).replace(/^tbl \$[0-9A-F]+: /, '')}`,
        `; ROM $${hex(t.base, 6)}, ${t.entries} entries x $${hex(t.size, 2)} bytes (entries counted up to the highest recorded index)`,
    ];
    if (site.index) lines.push('; index:  ' + site.index);
    if (site.result) lines.push('; result: ' + site.result);
    const readers = [...new Set(t.fields.flatMap(f => f.sites.map(s => index.describePc(s.pc))))];
    lines.push('; read by: ' + readers.slice(0, 6).join(', ') + (readers.length > 6 ? ', +' + (readers.length - 6) + ' more' : ''));
    if (t.fields.length > 1) lines.push('; fields: ' + t.fields.map(f => '+$' + hex(f.at, 2) + (f.width === 2 ? ' word' : ' byte')).join(', '));
    lines.push('; Edit values freely. Changing the entry count also needs the code that indexes it.', '');
    for (let k = 0; k < t.entries; k++) {
        const base = t.base + k * t.size;
        const parts = segs.map(sg => (sg.width === 2 ? 'dw $' + hex(readValue(rom, base + sg.at, 2), 4) : 'db $' + hex(rom[base + sg.at], 2)));
        lines.push('    ' + parts.join(' : ') + '    ; ' + k);
    }
    return lines.join('\n') + '\n';
}

function cType(width) { return width === 2 ? 'uint16_t' : 'uint8_t'; }

function headerText(assets) {
    const out = ['/* Generated by Everscript from the CDL library: ROM lookup tables (tables/*.asm is the source). */',
        '#pragma once', '#include <stdint.h>', ''];
    for (const a of assets) {
        const segs = a.layout;
        const comment = `/* ${a.title}${a.index ? '; index: ' + a.index : ''} */`;
        if (segs.length === 1) {
            const w = segs[0].width;
            out.push(comment, `static const ${cType(w)} ${a.name}[${a.entries}] = {`);
            for (let i = 0; i < a.values.length; i += 12) out.push('    ' + a.values.slice(i, i + 12).map(r => '0x' + hex(r[0], w * 2)).join(', ') + ',');
            out.push('};', '');
        } else {
            out.push(comment, 'typedef struct {');
            segs.forEach(sg => out.push(`    ${cType(sg.width)} ${sg.field ? 'f' : 'pad'}${hex(sg.at, 2)};`));
            out.push(`} ${a.name}_t;`, `static const ${a.name}_t ${a.name}[${a.entries}] = {`);
            for (const r of a.values) out.push('    { ' + r.map((v, i) => '0x' + hex(v, segs[i].width * 2)).join(', ') + ' },');
            out.push('};', '');
        }
    }
    return out.join('\n');
}

/**
 * @param tables  findTables() result
 * @param taken   Uint8Array(rom.length), 1 where a known region already sits
 * @returns {{ regions, files: [{ path, text }], skipped: string[] }}
 */
function buildTableAssets({ tables, rom, lib, map, index, taken }) {
    const regions = [], files = [], skipped = [], assets = [];
    const used = new Uint8Array(rom.length);
    for (const t of tables.slice().sort((a, b) => a.base - b.base)) {
        const name = 'tbl_' + hex(map.canonical(t.base), 6);
        const start = t.base, end = t.base + t.entries * t.size;
        let why = null;
        if (end - start < MIN_BYTES) why = 'too small';
        else if (end > rom.length || Math.floor(start / map.segment) !== Math.floor((end - 1) / map.segment)) why = 'crosses a bank';
        else if (!t.capped && t.idx.length * DENSITY < t.entries) why = `sparse (${t.idx.length} of ${t.entries} indices seen)`;
        else if (t.capped && t.entries > 0x800) why = 'very large, length not trusted';
        else {
            for (let o = start; o < end && !why; o++) {
                if (lib.cdl[o] & CDL_CODE) why = 'contains executed code';
                else if (taken[o]) why = 'overlaps a known region';
                else if (used[o]) why = 'overlaps another table';
            }
        }
        if (why) { skipped.push(name + ': ' + why); continue; }
        used.fill(1, start, end);
        const layout = recordLayout(t);
        const file = 'tables/' + name + '.asm';
        files.push({ path: file, text: assetText(t, rom, map, index, name) });
        regions.push({ start, end, kind: 'bytes', name, note: tableTitle(t, map).replace(/^tbl \$[0-9A-F]+: /, '') + ' (asset: ' + file + ')', lines: ['    incsrc "' + file + '"'], table: t });
        const values = [];
        for (let k = 0; k < t.entries; k++) values.push(layout.map(sg => readValue(rom, start + k * t.size + sg.at, sg.width)));
        const site = t.fields[0].sites[0];
        assets.push({
            name, file, romOffset: start, bus: map.canonical(start), entries: t.entries, entrySize: t.size, kind: t.kind,
            fields: t.fields.map(f => ({ offset: f.at, width: f.width })), layout, title: tableTitle(t, map),
            index: site.index || null, result: site.result || null,
            readers: t.fields.flatMap(f => f.sites.map(s => index.describePc(s.pc))), values,
        });
    }
    if (assets.length) {
        files.push({ path: 'tables/tables.json', text: JSON.stringify(assets.map(a => ({ ...a, layout: undefined, title: undefined })), null, 1) + '\n' });
        files.push({ path: 'tables/tables.h', text: headerText(assets) });
    }
    return { regions, files, skipped };
}

module.exports = { buildTableAssets, recordLayout };
